cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_MU_RED',10^(-7))
cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_INFEAS',10^(-7))
cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_REL_GAP',10^(-7))
cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_DFEAS',10^(-7)) 
cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_PFEAS',10^(-7)) 
cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_NEAR_REL',10^6) 
cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_MU_RED',10^(-5));
cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_REL_GAP',10^(-5))
cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_DFEAS',10^(-5)) 
cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_NEAR_REL',10^6) 
cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_PFEAS',10^(-5)) 
cvx_solver_settings('MSK_IPAR_BI_IGNORE_NUM_ERROR','MSK_ON') 
cvx_solver_settings('MSK_IPAR_OPTIMIZER','MSK_OPTIMIZER_FREE') 
cvx_solver_settings('MSK_DPAR_BASIS_TOL_X',10^(-3))
cvx_solver_settings('MSK_DPAR_BASIS_TOL_S',10^(-3)) 
cvx_solver_settings('MSK_DPAR_BASIS_REL_TOL_S',10^(-5))
cvx_solver_settings('MSK_IPAR_ANA_SOL_PRINT_VIOLATED','MSK_ON')
cvx_solver_settings('MSK_IPAR_INTPNT_SOLVE_FORM','MSK_SOLVE_FREE')
cvx_save_prefs

% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_MU_RED',10^(-10))
% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_INFEAS',10^(-10))
% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_REL_GAP',10^(-10))
% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_DFEAS',10^(-10)) 
% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_PFEAS',10^(-10)) 
% cvx_solver_settings('MSK_DPAR_INTPNT_CO_TOL_NEAR_REL',10^6) 
% cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_MU_RED',10^(-10));
% cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_REL_GAP',10^(-10))
% cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_DFEAS',10^(-10)) 
% cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_NEAR_REL',10^6) 
% cvx_solver_settings('MSK_DPAR_INTPNT_NL_TOL_PFEAS',10^(-10)) 
% cvx_solver_settings('MSK_IPAR_BI_IGNORE_NUM_ERROR','MSK_ON') 
% cvx_solver_settings('MSK_IPAR_OPTIMIZER','MSK_OPTIMIZER_FREE') 
% cvx_solver_settings('MSK_DPAR_BASIS_TOL_X',10^(-9))
% cvx_solver_settings('MSK_DPAR_BASIS_TOL_S',10^(-9)) 
% cvx_solver_settings('MSK_DPAR_BASIS_REL_TOL_S',10^(-10))
% cvx_solver_settings('MSK_IPAR_ANA_SOL_PRINT_VIOLATED','MSK_ON')
% cvx_solver_settings('MSK_IPAR_INTPNT_SOLVE_FORM','MSK_SOLVE_FREE')
% cvx_save_prefs
